#!/bin/bash

# 
# Copyright 2012-2017 University of Southern California
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# paths set for installation
VARLIBDIR=/var/lib/ermrest
LIBEXECDIR=/usr/libexec/ermrest
SHAREDIR=/usr/share/ermrest
SBINDIR=/usr/sbin
SU=su

# named parameters that can be set by caller or on command-line above to override defaults...
PGADMIN="${PGADMIN:-postgres}"

# make these available to child processes
export PGADMIN
export DAEMONUSER

TMP_SQL=$(mktemp /tmp/ermrest-update-extension.sql.XXXXX)

cleanup()
{
    rm -f ${TMP_SQL}
}

trap cleanup 0

emit_db_update()
{
    dbname="$1"
    cat <<EOF
\\connect "$dbname"
EOF
    $SU -c "psql -q -t -A -c \"SELECT extname FROM pg_catalog.pg_extension\" \"$dbname\"" - "${PGADMIN}" < /dev/null | {
	while read extname
	do
	    cat <<EOF
ALTER EXTENSION "$extname" UPDATE;
EOF
	done
    }
    cat <<EOF
REINDEX DATABASE "$dbname";
ANALYZE;

EOF
}

{
    $SU -c "psql -q -t -A -c \"SELECT descriptor::json->>'dbname' FROM ermrest.simple_registry\" ermrest" - "${PGADMIN}" | {
	emit_db_update "ermrest"
	while read cat_db
	do
	    emit_db_update "${cat_db}"
	done
    }
} > ${TMP_SQL}


$SU -c "psql --echo-all" - "${PGADMIN}" < ${TMP_SQL}

