#!/bin/sh

# 
# Copyright 2012-2015 University of Southern California
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# paths set for installation
VARLIBDIR=/var/lib/ermrest
LIBEXECDIR=/usr/libexec/ermrest
SHAREDIR=/usr/share/ermrest
SBINDIR=/usr/sbin

# named parameters that can be set by caller or on command-line above to override defaults...

DAEMONUSER="${DAEMONUSER:-ermrest}" # Unix and DB user name for service daemon

# make these available to child processes
export PGADMIN
export DAEMONUSER

# for all catalogs, do periodic maintenance of _ermrest.valuemap inverted table
runuser -c "psql -q -t -A -c \"SELECT id FROM ermrest.simple_registry\" ermrest" - "${DAEMONUSER}" | {
    while read cat_id
    do
	runuser -c "ermrest-valuemap-recreate ${cat_id}" - "${DAEMONUSER}"
    done
}

