#!/bin/sh

# 
# Copyright 2012-2013 University of Southern California
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# paths set for installation
VARLIBDIR=/var/lib/ermrest
LIBEXECDIR=/usr/libexec/ermrest
SHAREDIR=/usr/share/ermrest
SBINDIR=/usr/sbin

# named parameters that can be set by caller or on command-line above to override defaults...

DAEMONUSER="${DAEMONUSER:-ermrest}" # Unix and DB user name for service daemon

# make these available to child processes
export PGADMIN
export DAEMONUSER

# for all catalogs, do periodic maintenance of _ermrest version tracking
#  -- at runtime functions insert new versions 
#  -- readers use max() aggregation to find latest
#  -- periodically flush older version info
#  -- this works with postgres MVCC to avoid concurrent update hazards
runuser -c "psql -q -t -A -c \"SELECT descriptor::json->>'dbname' FROM ermrest.simple_registry\" ermrest" - "${DAEMONUSER}" | {
    while read cat_db
    do
	runuser -c "psql -q \"${cat_db}\"" - "${DAEMONUSER}" <<EOF
BEGIN;

-- purge older model versions
DELETE FROM _ermrest.model_version d
WHERE d.snap_txid < (SELECT max(snap_txid) 
                     FROM _ermrest.model_version
                     WHERE snap_txid < txid_snapshot_xmin(txid_current_snapshot())
                    )
;

-- purge older data versions
DELETE FROM _ermrest.data_version d
USING (
  SELECT "schema", "table", max(snap_txid) AS snap_txid
  FROM _ermrest.data_version
  WHERE snap_txid < txid_snapshot_xmin(txid_current_snapshot())
  GROUP BY "schema", "table"
) c
WHERE d."schema" = c."schema"
  AND d."table" =  c."table"
  AND d.snap_txid < c.snap_txid 
;

COMMIT;
EOF
    done
}

