#!/bin/bash

# 
# Copyright 2012-2013 University of Southern California
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [[ $# -gt 0 ]]
then
    # allow VAR=value args to be passed on command-line
    exec /bin/env "$@" "$0"
fi

# named parameters that can be set by caller or on command-line above to override defaults...

PGADMIN="${PGADMIN:-postgres}"

DAEMONUSER="${DAEMONUSER:-ermrest}" # Unix and DB user name for service daemon
USERDEL="${USERDEL:-false}"         # whether to try to destroy Unix daemon account
DROPUSER="${CREATEUSER:-false}"     # whether to try to destroy PostgreSQL role

DROPDB="${DROPDB:-false}"           # whether to try to drop service database

DEPLOYLOCK="${DEPLOYLOCK}"

SU=su

undeploy()
{
    # TODO: drop multi-tenant catalogs here?
    # TODO: nuke WSGI config here?
    [[ "$DROPDB" = "true" ]] && $SU -c "dropdb \"$DAEMONUSER\"" - "${PGADMIN}"
    [[ "$DROPUSER" = "true" ]] && $SU -c "dropuser -w \"$DAEMONUSER\"" - "${PGADMIN}"
    [[ "$USERDEL" = "true" ]] && userdel -r "$DAEMONUSER"
}

if [[ -n "$DEPLOYLOCK" ]]
then
    [[ -r "$DEPLOYLOCK" ]] || {
	echo could not read deployment lock $DEPLOYLOCK >&2
	exit 1
    }
    . "$DEPLOYLOCK"
    undeploy
    rm -f "$DEPLOYLOCK"
else
    undeploy
fi


