CREATE SCHEMA cirm;

CREATE TABLE cirm.box
  (
    id varchar(30) PRIMARY KEY,
    "Section Date" date NOT NULL,
    "Sample Name" varchar(15) NOT NULL,
    "Initials" varchar(3) NOT NULL,
    "Disambiguator" char(1) NOT NULL,
    "Comment" text,
    "Tags" text
  );

-- these indices must match the expression generated by src/model.py:FreetextColumn to be useful
-- need same columns (all text and character types)
-- need same typecasts
-- need same coalescing of NULLs
-- need same concatenation order (based on table column ordinal)
CREATE INDEX ON cirm.box USING gin ( 
  (to_tsvector('english'::regconfig, 
  	       COALESCE(id::text, ''::text) 
	       || ' ' || COALESCE("Sample Name"::text, ''::text) 
	       || ' ' || COALESCE("Initials"::text, ''::text) 
	       || ' ' || COALESCE("Disambiguator"::text, ''::text) 
	       || ' ' || COALESCE("Comment"::text, ''::text) 
	       || ' ' || COALESCE("Tags"::text, ''::text)
	      )
  ) 
);

CREATE TABLE cirm.experiment
  (
    id varchar(30) PRIMARY KEY,
    "Experiment Date" date NOT NULL,
    "Experiment Description" varchar(15) NOT NULL,
    "Initials" varchar(3) NOT NULL,
    "Disambiguator" char(1) NOT NULL,
    "Comment" text,
    "Tags" text
  );

CREATE INDEX ON cirm.experiment USING gin ( 
  (to_tsvector('english'::regconfig, 
  	       COALESCE(id::text, ''::text) 
	       || ' ' || COALESCE("Experiment Description"::text, ''::text) 
	       || ' ' || COALESCE("Initials"::text, ''::text) 
	       || ' ' || COALESCE("Disambiguator"::text, ''::text) 
	       || ' ' || COALESCE("Comment"::text, ''::text) 
	       || ' ' || COALESCE("Tags"::text, ''::text)
	      )
  ) 
);

CREATE TABLE cirm.slide
  (
    id varchar(37) PRIMARY KEY,
    "Seq." integer NOT NULL,
    "Rev." integer NOT NULL,
    "Box ID" varchar(30) NOT NULL,
    "Experiment ID" varchar(30),
    "Comment" text,
    "Tags" text,
    FOREIGN KEY ("Box ID") REFERENCES cirm.box (id),
    FOREIGN KEY ("Experiment ID") REFERENCES cirm.experiment (id)
  );

CREATE INDEX ON cirm.slide USING gin ( 
  (to_tsvector('english'::regconfig, 
  	       COALESCE(id::text, ''::text) 
	       || ' ' || COALESCE("Box ID"::text, ''::text) 
	       || ' ' || COALESCE("Experiment ID"::text, ''::text) 
	       || ' ' || COALESCE("Comment"::text, ''::text) 
	       || ' ' || COALESCE("Tags"::text, ''::text)
	      )
  ) 
);


CREATE TABLE cirm.scan
  (
    id text PRIMARY KEY,
    slide_id varchar(37),
    original_filename text,
    go_endpoint text,
    go_path text,
    http_url text,
    filename text,
    filesize bigint,
    thumbnail text,
    tilesdir text,
    zoomify text,
    "Comment" text,
    "Tags" text,
    FOREIGN KEY (slide_id) REFERENCES cirm.slide (id)
  );

CREATE INDEX ON cirm.scan USING gin ( 
  (to_tsvector('english'::regconfig, 
  	       COALESCE(id::text, ''::text) 
	       || ' ' || COALESCE(slide_id::text, ''::text) 
	       || ' ' || COALESCE(filename::text, ''::text) 
	       || ' ' || COALESCE(thumbnail::text, ''::text) 
	       || ' ' || COALESCE(tilesdir::text, ''::text) 
	       || ' ' || COALESCE("Comment"::text, ''::text) 
	       || ' ' || COALESCE("Tags"::text, ''::text)
	      )
  ) 
);

SET client_min_messages=ERROR;
VACUUM ANALYZE;

