CREATE SCHEMA cirm;

CREATE TABLE cirm.box
  (
    id varchar(30) PRIMARY KEY,
    section_date date NOT NULL,
    sample_name varchar(15) NOT NULL,
    initials varchar(3) NOT NULL,
    disambiguator char(1) NOT NULL,
    comment text,
    tags text
  );

-- these indices must match the expression generated by src/model.py:FreetextColumn to be useful
-- need same columns (all text and character types)
-- need same typecasts
-- need same coalescing of NULLs
-- need same concatenation order (based on table column ordinal)
CREATE INDEX ON cirm.box USING gin ( 
  (to_tsvector('english'::regconfig, 
  	       COALESCE(id::text, ''::text) 
	       || ' ' || COALESCE(sample_name::text, ''::text) 
	       || ' ' || COALESCE(initials::text, ''::text) 
	       || ' ' || COALESCE(disambiguator::text, ''::text) 
	       || ' ' || COALESCE(comment::text, ''::text) 
	       || ' ' || COALESCE(tags::text, ''::text)
	      )
  ) 
);

CREATE TABLE cirm.experiment
  (
    id varchar(30) PRIMARY KEY,
    experiment_date date NOT NULL,
    experiment_description varchar(15) NOT NULL,
    initials varchar(3) NOT NULL,
    disambiguator char(1) NOT NULL,
    comment text,
    tags text
  );

CREATE INDEX ON cirm.experiment USING gin ( 
  (to_tsvector('english'::regconfig, 
  	       COALESCE(id::text, ''::text) 
	       || ' ' || COALESCE(experiment_description::text, ''::text) 
	       || ' ' || COALESCE(initials::text, ''::text) 
	       || ' ' || COALESCE(disambiguator::text, ''::text) 
	       || ' ' || COALESCE(comment::text, ''::text) 
	       || ' ' || COALESCE(tags::text, ''::text)
	      )
  ) 
);

CREATE TABLE cirm.slide
  (
    id varchar(37) PRIMARY KEY,
    sequence_num integer NOT NULL,
    revision integer NOT NULL,
    box_of_origin_id varchar(30) NOT NULL,
    experiment_id varchar(30),
    comment text,
    tags text,
    FOREIGN KEY (box_of_origin_id) REFERENCES cirm.box (id),
    FOREIGN KEY (experiment_id) REFERENCES cirm.experiment (id)
  );

CREATE INDEX ON cirm.slide USING gin ( 
  (to_tsvector('english'::regconfig, 
  	       COALESCE(id::text, ''::text) 
	       || ' ' || COALESCE(box_of_origin_id::text, ''::text) 
	       || ' ' || COALESCE(experiment_id::text, ''::text) 
	       || ' ' || COALESCE(comment::text, ''::text) 
	       || ' ' || COALESCE(tags::text, ''::text)
	      )
  ) 
);


CREATE TABLE cirm.scan
  (
    id varchar(41) PRIMARY KEY,
    slide_id varchar(37),
    scan_num integer NOT NULL,
    endpoint text,
    filename text,
    filesize bigint,
    thumbnail text,
    tilesdir text,
    zoomify text,
    comment text,
    tags text,
    FOREIGN KEY (slide_id) REFERENCES cirm.slide (id)
  );

CREATE INDEX ON cirm.scan USING gin ( 
  (to_tsvector('english'::regconfig, 
  	       COALESCE(id::text, ''::text) 
	       || ' ' || COALESCE(slide_id::text, ''::text) 
	       || ' ' || COALESCE(filename::text, ''::text) 
	       || ' ' || COALESCE(thumbnail::text, ''::text) 
	       || ' ' || COALESCE(tilesdir::text, ''::text) 
	       || ' ' || COALESCE(comment::text, ''::text) 
	       || ' ' || COALESCE(tags::text, ''::text)
	      )
  ) 
);

SET client_min_messages=ERROR;
VACUUM ANALYZE;

